### ISSUE TITLE
Error run on windows

### ISSUE THREAD

**Issue by shaiful73** [Jigsaw-Code/outline-go-tun2socks#130]
I am trying to run the project using go run .\outline\electron\main.go
but I get this error:
# github.com/Jigsaw-Code/outline-go-tun2socks/tunnel
tunnel\tunnel.go:36:19: undefined: core.LWIPStack
tunnel\tunnel.go:60:57: undefined: core.LWIPStack

**Comment by daniellacosse** [comment]
This currently isn't supported. If you want to try the network stack, we recommend looking at [our SDK](https://github.com/Jigsaw-Code/outline-sdk/tree/main/network)! [Here's an example of how to use it!](https://github.com/Jigsaw-Code/outline-sdk/tree/main/x/examples/outline-cli)
