### ISSUE TITLE
How can we support v2ray-plugin in this project?

### ISSUE THREAD

**Issue by giftedunicorn** [Jigsaw-Code/outline-go-tun2socks#45]
I see this project uses go-shadowsocks2, and go-ss2 suppose to support v2ray-plugin. 

I just want to know how to integrate v2ray-plugin into this project? 

Or any plan to add this feature?

**Comment by bemasc** [comment]
Sorry for the delayed response.  We aren't planning to add v2ray support at this time, but feel free to experiment with the code by duplicating the Outline connection handlers and let us know if you learn anything.
