### ISSUE TITLE
Documentation - Encryption Methods

### ISSUE THREAD

**Issue by Taher-17** [Jigsaw-Code/outline-go-tun2socks#48]
I have noticed that there is no documentation regarding which encryption methods are and aren't supported. I also think it would be helpful to point people in the right direction if they want to add an encryption method that isn't supported.

From my testing, I found that these methods to not be supported:

```
CHACHA20
AES-256-CFB
```

This is the one I found that was supported:

```
CHACHA20-IEFT-POLY1305
```

**Comment by chinsyo** [comment]
go-shadowsocks2 have remove stream cipher, include aes-cfb, aes-ctr, chacha20.
