### ISSUE TITLE
Optimize memory usage with go-shadowsocks2 in bloomring for defense replay attack.

### ISSUE THREAD

**Issue by chinsyo** [Jigsaw-Code/outline-go-tun2socks#51]
Hi, outline-go-tun2socks is such a brilliant project that really inspired me.

15Mb memory limit on iOS platform is a big challenge, and I think the dependency go-shadowsocks2 bloomring module alloc about 1Mb memory to defense replay attack in client is a little bit luxurious.

Could you please change the bloomring feature to optional?

**Comment by chinsyo** [comment]
refer to [https://github.com/shadowsocks/go-shadowsocks2/issues/171](url) @alalamav

**Comment by chinsyo** [comment]
I guess default capacity 1e6 means at least 1Mb memory usage. https://github.com/shadowsocks/go-shadowsocks2/blob/ff604f980c3b8f9cbbad6b8da8d50553327a9b36/internal/saltfilter.go

**Comment by alalamav** [comment]
Hi @chinsyo, outline-go-tun2socks depends on [outline-ss-server](https://github.com/Jigsaw-Code/outline-ss-server), which uses components of go-shadowsocks2. outline-ss-server recently implemented its own version of replay attack protection on the server, but the client is not affected. 

As you mentioned, iOS is memory constrained, so we're working on reducing memory usage both in the client and server.

I'm glad you like this project :)

**Comment by chinsyo** [comment]
> Hi @chinsyo, outline-go-tun2socks depends on [outline-ss-server](https://github.com/Jigsaw-Code/outline-ss-server), which uses components of go-shadowsocks2. outline-ss-server recently implemented its own version of replay attack protection on the server, but the client is not affected.
> 
> As you mentioned, iOS is memory constrained, so we're working on reducing memory usage both in the client and server.
> 
> I'm glad you like this project :)

Thanks for your reply.
